// AUTHENTICATION
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

// CHAT
export const GET_MESSAGES = 'GET_MESSAGES';
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES';
export const SET_MESSAGE_PAGE_LIST = 'SET_MESSAGE_PAGE_LIST';

// ITEMS
export const SET_ITEM_LIST = 'SET_ITEM_LIST';