// AUTHENTICATION
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

// CHAT
export const GET_MESSAGES = 'GET_MESSAGES';
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES';
export const SET_MESSAGE_PAGE_LIST = 'SET_MESSAGE_PAGE_LIST';
export const CLEAR_SAVED_MESSAGES = 'CLEAR_SAVED_MESSAGES';
export const SET_LOADING = 'SET_LOADING';
export const ADD_MESSAGE = 'ADD_MESSAGE';

// ITEMS
export const SET_ITEM_LIST = 'SET_ITEM_LIST';
export const FILTER_ITEMS = 'FILTER_ITEMS';